plugins {
    id 'com.android.application'
}

android {
    namespace 'com.esnexius.sitemanager'
    compileSdk 35

    defaultConfig {
        applicationId 'com.esnexius.sitemanager'
        minSdk 28
        targetSdk 28
        versionCode 3
        versionName '1.0.2-android9'
    }

    signingConfigs {
        debug {
            enableV1Signing true
            enableV2Signing true
            enableV3Signing false
            enableV4Signing false
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
